space add
starboy-3/PersonalRecommendationsApp pull request #5
Opened 2022-01-26 22:01 UTC by FPSarmin

2022-01-26 22:02 UTC, starboy-3 requested changes

2022-01-26 22:02 UTC, starboy-3 commented on app/scrapy.cfg
> +
wtf man

2022-01-26 22:02 UTC, FPSarmin commented on app/scrapy.cfg
> +
fu man

2022-02-13 18:28 UTC, starboy-3 commented
Паша подтяни мастер и добавь еще seller_id из href-a можешь распарсить
<img width="602" alt="image" src="https://user-images.githubusercontent.com/72921287/153769171-0d89d705-4597-4d8f-837c-f807dda26bef.png">

2022-05-18 22:02 UTC, merged